### ISSUE TITLE
No process when using with postcss-import

### ISSUE THREAD

**Issue by julzmon** [csstools/postcss-nesting#84] opened 2021-08-17 16:22 UTC
I can't get the nesting plugin to work with postcss-import. Nesting does work when in the main styles file that imports all the rest of files but does not work nested markup is @imported. This is running in a 11ty project.

postcss.config.js
```
module.exports = {
  plugins: [
    require(`tailwindcss`)(`./src/styles/tailwind.config.js`),
    require('postcss-import'),
    require('postcss-nesting'),
    require(`stylelint`),
    require(`autoprefixer`),
  ]
};
```

tailwind.css
```
@import "_reset.css";
@import "_table.css";

/* @tailwind base; */
@tailwind utilities;

.red {
  color: var(--something);
  & .blue {
    color: var(--something);
  }
}
```

**Comment by caschbre** [comment] 2021-10-06 00:02
I'm also running into this issue.  I originally had my css inside of a Svelte <style> tag. I could use the @nest operator per the spec and it worked great. Then I moved all of my css to individual .css files and imported them using postcss-import.  The @nest operator stopped working.

I'm also have tailwindcss as a plugin, however I'm using postcss-preset-env with nesting-rules: true option set.

Some of the nesting works, however it was the @nest that I noticed stopped for me.

**Comment by romainmenke** [comment] 2021-10-30 10:40
Can you create a repo with a reproducible example?
I just tried to recreate the issue but nesting just works here. :/

**Comment by romainmenke** [comment] 2021-12-22 19:09
@julzmon This repo has been moved to https://github.com/csstools/postcss-plugins and will be archived soon.

If you still have issues with this please open a new issue there.
We're happy to assist you further in getting this resolved!

As we can't reproduce this as is it would be really helpful to have a github repo with an example of the issue.

Closing this issue as it's not possible to comment on issues in archived repo's.

**Closed by romainmenke** 2021-12-22 19:09 UTC
